Update README.md
[This](https://github.com/jyu213/ssh2-sftp-client/blob/master/src/index.js#L78) will cause failures in older versions of node:
```
SyntaxError: Unexpected token {
```
I suppose that instead of mentioning node version compatibility here, you could:
- remove destructuring from `https://github.com/jyu213/ssh2-sftp-client/blob/master/src/index.js`
- transpile `index.js` to output an older version of js before packaging